# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Marcel Braghetto
tagline:          'My random coding stuff'
description:      'My random coding stuff'
url:              https://marcelbraghetto.github.io
baseurl:          /

author:
  name:           'Marcel Braghetto'
  url:            https://marcelbraghetto.github.io

paginate:         5

excerpt_separator: <!-- excerpt -->