# Dependencies
plugins:            [jekyll-paginate]
markdown:           kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
highlighter:        rouge

# Permalinks
permalink:          pretty

# Setup
title:              Marcel Braghetto
tagline:            'My random coding stuff'
description:        'My random coding stuff'
url:                https://marcelbraghetto.github.io

author:
  name:             'Marcel Braghetto'
  url:              https://marcelbraghetto.github.io

paginate:           1000

excerpt_separator:  <!-- excerpt -->
future: true